### ISSUE TITLE
Task list milestone 1

### ISSUE THREAD

**Issue by sreejithmunthikodu** [UBC-MDS/KmeansR#1]
- [x] Choose a project
- [x] Create a project structure for R project
- [x] Write empty functions and docstrings
- [x] Create teamwork document
- [x] Create CONTRIBUTORS.md
- [x] Create CONDUCT.md
- [x] Create CONTRIBUTING.md
- [x]  Create README.md
